# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'vs2017-win2016'

steps:
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '7.0.1'
    executeArgs: 'browserType="Web Service" -executionProfile="DEV_Profile" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/All Test Cases"'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
